rooms = [
    {
        "name": "G1",
        "single_beds": 2,
        "couple_beds": 1,
        "price_by_day": 100.00,
        "description": "Private room with two single beds and a double bed, with bathroom. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque blandit lacus aliquam erat aliquet sodales. Aenean sagittis laoreet diam, id efficitur diam efficitur fringilla. Aenean congue, orci lacinia pharetra elementum, lorem quam sollicitudin dui, non fermentum enim neque a ante. Nam id sapien nec leo faucibus sollicitudin. Pellentesque pellentesque, nibh non tempor vestibulum, nulla lorem blandit neque, in volutpat arcu purus in elit. Sed ultricies lacinia ligula, nec dictum felis imperdiet id. Duis vestibulum quis lorem eget tempor. ",
        "category": 4,
    },
    {
        "name": "G2",
        "single_beds": 2,
        "couple_beds": 1,
        "price_by_day": 100.00,
        "description": "Private room with two single beds and a double bed, with bathroom. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque blandit lacus aliquam erat aliquet sodales. Aenean sagittis laoreet diam, id efficitur diam efficitur fringilla. Aenean congue, orci lacinia pharetra elementum, lorem quam sollicitudin dui, non fermentum enim neque a ante. Nam id sapien nec leo faucibus sollicitudin. Pellentesque pellentesque, nibh non tempor vestibulum, nulla lorem blandit neque, in volutpat arcu purus in elit. Sed ultricies lacinia ligula, nec dictum felis imperdiet id. Duis vestibulum quis lorem eget tempor. ",
        "category": 4,
    },
    {
        "name": "G3",
        "single_beds": 4,
        "couple_beds": 1,
        "price_by_day": 90.00,
        "description": "Private room with four single beds and one double bed, no bathroom. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque blandit lacus aliquam erat aliquet sodales. Aenean sagittis laoreet diam, id efficitur diam efficitur fringilla. Aenean congue, orci lacinia pharetra elementum, lorem quam sollicitudin dui, non fermentum enim neque a ante. Nam id sapien nec leo faucibus sollicitudin. Pellentesque pellentesque, nibh non tempor vestibulum, nulla lorem blandit neque, in volutpat arcu purus in elit. Sed ultricies lacinia ligula, nec dictum felis imperdiet id. Duis vestibulum quis lorem eget tempor. ",
        "category": 1,
    },
    {
        "name": "G4",
        "single_beds": 8,
        "couple_beds": 0,
        "price_by_day": 80.00,
        "description": "Private room with eight single beds, no bathroom. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque blandit lacus aliquam erat aliquet sodales. Aenean sagittis laoreet diam, id efficitur diam efficitur fringilla. Aenean congue, orci lacinia pharetra elementum, lorem quam sollicitudin dui, non fermentum enim neque a ante. Nam id sapien nec leo faucibus sollicitudin. Pellentesque pellentesque, nibh non tempor vestibulum, nulla lorem blandit neque, in volutpat arcu purus in elit. Sed ultricies lacinia ligula, nec dictum felis imperdiet id. Duis vestibulum quis lorem eget tempor. ",
        "category": 1,
    },
    {
        "name": "G5",
        "single_beds": 0,
        "couple_beds": 1,
        "price_by_day": 90.00,
        "description": "Private Room with one double bed, with bathroom. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque blandit lacus aliquam erat aliquet sodales. Aenean sagittis laoreet diam, id efficitur diam efficitur fringilla. Aenean congue, orci lacinia pharetra elementum, lorem quam sollicitudin dui, non fermentum enim neque a ante. Nam id sapien nec leo faucibus sollicitudin. Pellentesque pellentesque, nibh non tempor vestibulum, nulla lorem blandit neque, in volutpat arcu purus in elit. Sed ultricies lacinia ligula, nec dictum felis imperdiet id. Duis vestibulum quis lorem eget tempor. ",
        "category": 2,
    },
]
