from .user import UserViewSet
from .category import CategoryViewSet
from .discount_coupon import DiscountCouponViewSet
from .service import ServiceViewSet
from .promotion import PromotionViewSet
from .room import RoomViewSet
from .booking import BookingViewSet
from .room_availability import RoomAvailabilityViewSet
from .booking_service import BookingServiceViewSet