# Generated by Django 5.1.2 on 2024-10-21 14:32

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='personal_info',
            field=models.JSONField(default=core.models.user.User.jsonfield_default_value, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica que este usuário é um funcionário da empresa.', verbose_name='Usuário é um funcionário'),
        ),
    ]
