# Generated by Django 5.1.2 on 2024-10-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_discountcoupon_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.IntegerField(max_length=2)),
                ('expiration_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
