# Generated by Django 5.1.2 on 2024-10-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_promotion_alter_discountcoupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_percentage',
            field=models.IntegerField(),
        ),
    ]
