# Generated by Django 5.1.2 on 2024-10-22 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_options_alter_discountcoupon_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'CANCELED'), (3, 'COMPLETED')], default=1)),
                ('booking_date', models.DateField()),
                ('discount_coupon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.discountcoupon')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.user')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
