# Generated by Django 5.1.2 on 2024-10-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_room_options_room_name_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('room_status', models.IntegerField(choices=[(1, 'RESERVED'), (2, 'MAINTENANCE')], default=1)),
                ('booking', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.booking')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
            options={
                'verbose_name': 'Room Availability',
                'verbose_name_plural': 'Room Availability',
            },
        ),
    ]
