# Generated by Django 5.1.2 on 2024-10-23 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_roomavailability_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='core.service')),
            ],
            options={
                'verbose_name': 'Booking Service',
                'verbose_name_plural': 'Bookings Services',
            },
        ),
    ]
