# Generated by Django 5.1.2 on 2024-10-23 15:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellation',
            name='cancellation_date',
            field=models.DateField(default=datetime.date(2024, 10, 23)),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'PAID')], default=1)),
                ('payment_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.IntegerField(choices=[(1, 'CREDIT CARD'), (2, 'DEBIT CARD'), (3, 'CASH'), (4, 'PIX')], default=4)),
                ('booking', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
