# Generated by Django 5.1.2 on 2024-10-23 22:26

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_cancellation_cancellation_date_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_status', models.IntegerField(blank=True, choices=[(1, 'PENDING'), (2, 'DECLINED'), (3, 'APPROVED')], default=1, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(default='No comments.', max_length=255)),
                ('feedback_date', models.DateField(default=datetime.date(2024, 10, 23))),
                ('booking', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
