# Generated by Django 5.1.2 on 2024-10-23 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='core.room')),
            ],
            options={
                'verbose_name': 'Booking Room',
                'verbose_name_plural': 'Bookings Rooms',
            },
        ),
    ]
