# Generated by Django 5.1.2 on 2024-10-23 22:56

import core.models.user
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bookingroom'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates that this user is active.', verbose_name='Usuário is active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indicates that this user is a company employee.', verbose_name='User is an employee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_info',
            field=models.JSONField(default=core.models.user.User.jsonfield_default_value, help_text='Personal info about the User.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.IntegerField(help_text="User's cell phone.", unique=True, verbose_name='telephone'),
        ),
    ]
