# Generated by Django 5.1.2 on 2024-10-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='name',
            field=models.CharField(default='No Promotion Name Given', max_length=50),
        ),
    ]
