# Generated by Django 5.1.2 on 2024-10-24 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_promotion_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellation',
            name='cancellation_fee',
        ),
    ]
