# Generated by Django 5.1.2 on 2024-10-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_cancellation_cancellation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
