# Generated by Django 5.1.2 on 2024-10-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_payment_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
