# Generated by Django 5.1.2 on 2024-10-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_payment_price_payment_booking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcoupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
