# Generated by Django 5.1.2 on 2024-10-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_discountcoupon_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcoupon',
            name='active',
        ),
    ]
